### ISSUE TITLE
Cant build

### ISSUE THREAD

**Issue by labs20** [Astro36/word2vec4node#1]
Hi! I'm not being able to build it.

Can you help, please?

```

> word2vec4node@0.1.0 install /Volumes/Work/Developer/Web/rdr_playground/node_modules/word2vec4node
> node-gyp rebuild

  CXX(target) Release/obj.target/word2vec/lib/word2vec.o
../lib/word2vec.cc:92:10: error: use of undeclared identifier 'fgetc_unlocked'; did you mean 'getc_unlocked'?
    ch = fgetc_unlocked(fin);
         ^~~~~~~~~~~~~~
         getc_unlocked
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/stdio.h:293:6: note: 'getc_unlocked' declared here
int      getc_unlocked(FILE *);
         ^
1 error generated.
make: *** [Release/obj.target/word2vec/lib/word2vec.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Darwin 18.7.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Volumes/Work/Developer/Web/rdr_playground/node_modules/word2vec4node
gyp ERR! node -v v14.9.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '/Volumes/Work/Developer/Web/rdr_playground/package.json'
npm WARN ts-type@1.2.32 requires a peer of @types/bluebird@* but none is installed. You must install peer dependencies yourself.
npm WARN rdr_playground No description
npm WARN rdr_playground No repository field.
npm WARN rdr_playground No README data
npm WARN rdr_playground No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! word2vec4node@0.1.0 install: `node-gyp rebuild`
npm ERR! Exit status 1

```

Thanks!

**Comment by Astro36** [comment]
I think some linux functions don't seem to work on the Mac: https://github.com/tmikolov/word2vec/issues/48
I couldn't test it because I didn't have Mac OS, but it probably works because I modified it by referring to the PR(https://github.com/tmikolov/word2vec/pull/40).
Thanks!

**Comment by labs20** [comment]
Hi. Thanks for the update.

Building fine now.

Thanks!
